---
name: Tailscale
version: dev
slug: tailscale
description: Zero config VPN for building secure networks
url: https://github.com/elcajon-tech/addon-tailscale
codenotary: codenotary@elcajon.dev
ingress: true
ingress_port: 0
ingress_stream: true
startup: services
panel_icon: mdi:vpn
arch:
  - aarch64
  - amd64
init: false
hassio_api: true
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
map:
  - config:rw
  - share:rw
  - backup:rw
  - media:rw
  - addons:rw
  - ssl:rw
schema:
  tags: ["match(^tag:[a-zA-Z0-9]-?[a-zA-Z0-9]+$)?"]
  enable_ssh: bool?
  enable_exit_node: bool?
  enable_subnets: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
